### ISSUE TITLE
Please clarify how named and positional parameters get bound

### ISSUE THREAD

**Issue by rybakit** [tarantool/doc#1096]
Let's consider the following example:

```lua
box.execute([[ DROP TABLE IF EXISTS exec_query ]])
box.execute([[ CREATE TABLE exec_query (id INTEGER PRIMARY KEY, name VARCHAR(50)) ]])
box.execute([[ INSERT INTO exec_query VALUES (1, 'A'), (2, 'B') ]])
```

The below code works just fine and returns `[2, 'B']`:

```lua
params = {}
params[1] = 2
params[2] = {}
params[2][':name'] = 'B'
box.execute([[ SELECT * FROM exec_query WHERE id = ? AND name = :name ]], params)
---
- metadata:
  - name: ID
    type: integer
  - name: NAME
    type: string
  rows:
  - [2, 'B']
```

However, if I change the order of the passed parameters, it seems that the algorithm cannot correctly bind them anymore, even if one of the parameters is clearly given a name, so there is no ambiguity:

```
params = {}
params[1] = 'B'
params[2] = {}
params[2][':id'] = 2
box.execute([[ SELECT * FROM exec_query WHERE id = :id AND name = ? ]], params)
---
- metadata:
  - name: ID
    type: integer
  - name: NAME
    type: string
  rows: []
```

From the user's point of view, this behavior (unless it's a bug) is confusing, so, IMHO, it should be documented.

**Comment by pgulutzan** [comment]
I failed to mention named parameters at all, I have fixed that and given what I hope are better examples. As for the confusion with parameter ordering, if I understand the comment in issue#4760, there was a bug in the implementation.

**Comment by rybakit** [comment]
@pgulutzan Thanks for the examples. As for the order of parameters, this is not a bug but the intended behavior (at least what I understood from @Korablev77), and the bug he was talking about was in the wrong position of the named parameters, gh-4760 (`i` instead of `i+1`). Nikita, please correct me if I'm wrong. If my assumption is correct, then the behavior showed above needs to be explained in detail because (IMHO) is not obvious at all.

**Comment by pgulutzan** [comment]
Suppose we set the params as in the second example:
params = {}
params[1] = 'B'
params[2] = {}
params[2][':id'] = 2
And then we say
box.execute([[ SELECT ?, :id FROM exec_query WHERE id = :id; ]], params)
Result: one row containing 'B', 2.
To me, this means that ? is correctly interpreted as 'B' and :id is
correctly interpreted as 2. I admit it looks odd but the examples in
the manual show that named parameters and ? placeholders are set up
differently. So I think the manual examples are correct.
And then we say
box.execute([[ SELECT ?, :id FROM exec_query WHERE name = ?; ]], params)
Result: nothing.
But, since we have confirmed that ? is correctly interpreted as 'B',
I cannot see a way to explain that.
Therefore I think there is an implementation bug,
although perhaps Korablev77 can correct me.

**Comment by rybakit** [comment]
>  I cannot see a way to explain that.

Me either :) Here is a simplified example:

```lua
box.execute([[ SELECT ?, :id; ]], params)
---
- metadata:
  - name: '?'
    type: text
  - name: :id
    type: integer
  rows:
  - ['B', 2]
```

```lua
box.execute([[ SELECT :id, ?; ]], params)
---
- metadata:
  - name: :id
    type: integer
  - name: '?'
    type: boolean
  rows:
  - [2, null]
```

**Comment by Korablev77** [comment]
Answered here: https://github.com/tarantool/tarantool/issues/4782#issuecomment-588398960
