### ISSUE TITLE
Add a description of missing methods of box.tuple

### ISSUE THREAD

**Issue by olegrok** [tarantool/doc#1123]
https://www.tarantool.io/en/doc/1.10/reference/reference_lua/box_tuple/

"next", "ipairs", "slice" and "upsert" are not documented

**Comment by Totktonada** [comment]
AFAIR, I was wonder why slice is not documented and did come to the conclusion that tuple:transform() is the replacement for it. Now I found only the [commit][1], where the related docs were removed, and mention is the [issue][2] about plans to remove tuple:slice() from docs.

[1]: https://github.com/tarantool/tarantool/commit/e079d22ad77d39cb7f4ba6efa8c635979f6e67be#diff-612534e4568cc786726dc921e3585716L2082
[2]: https://github.com/tarantool/tarantool/issues/454#issuecomment-89847462

**Comment by Gerold103** [comment]
Here is my docbot request, which apparently was created after Oleg's ticket, because I missed it. It may help.

```Lua
tuple_object:next(pos)
```
An analogue of Lua `next()` function, but for a tuple object.
Although `tuple:next()` is not really efficient, and it is better
to use `tuple:pairs()/ipairs()`.
```
tarantool> t = box.tuple.new({1, 2, 3})
tarantool> ctx, field = t:next()
tarantool> while field do
    print(field)
    ctx, field = t:next(ctx)
end
tarantool>
1 2 3
```

```Lua
tuple_object:ipairs()
```
The same as `tuple_object:pairs()`. Because tuple fields are
integer always.

```Lua
tuple_object:upsert()
```
The same as `tuple_object:update()`, but ignores errors. In case
of an error the tuple is left intact, but an error message is
printed. Only client errors are ignored, such as a bad field type,
or wrong field index/name. System errors, such as OOM, are not
ignored and raised just like with normal `update()`. Note, that
only bad operations are ignored. All correct operations are
applied.
```
tarantool> t = box.tuple.new({1, 2, 3})
tarantool> t2 = t:upsert({{'=', 5, 100}})
UPSERT operation failed:
ER_NO_SUCH_FIELD_NO: Field 5 was not found in the tuple
---
...

tarantool> t
---
- [1, 2, 3]
...

tarantool> t2
---
- [1, 2, 3]
...

tarantool> t2 = t:upsert({{'=', 5, 100}, {'+', 1, 3}})
UPSERT operation failed:
ER_NO_SUCH_FIELD_NO: Field 5 was not found in the tuple
---
...

tarantool> t
---
- [1, 2, 3]
...

tarantool> t2
---
- [4, 2, 3]
...
```
See how in the last example one operation is applied, and one is
not.

All methods of `tuple_object` are also available in `box.tuple.*`,
and a tuple needs to be passed explicitly then. Example below:
```
tarantool> t = box.tuple.new({1, 2, 3})
tarantool> box.tuple.slice(t, 0, 1)
---
- 1
...
```
