### ISSUE TITLE
Extend SQL compliance table

### ISSUE THREAD

**Issue by tsafin** [tarantool/doc#1168]
We have great [SQL compliance page](https://www.tarantool.io/en/doc/2.2/book/sql/) but comparing to [PostgreSQL one](https://www.postgresql.org/docs/11/features-sql-standard.html) we see that list is much, much shorter than it has to be. We should extend it with newer parts.

**Comment by pgulutzan** [comment]
Our list is for mandatory (core) features.
PostgreSQL's list is longer because they claim to support some optional (non-core) features.
If we added non-core features to our list, then we would have to say "Fail" for almost all of them,
and I don't see how that helps anybody. So I oppose this idea.

However, I did some comparisons to see whether we missed something regarding the core.
I found that:

F021 Basic information_schema -- we omitted, our list is for items in 9075-2 (I think concentrating on 9075-2 is the right thing to do)
F051-09 LOCALTIMESTAMP -- my mistake, we have the wrong numbers for some F051 items
F131-05 Single row SELECT with GROUP BY and HAVING clauses and grouped views -- my mistake, this should be included
F501 Features and conformance views --  we omitted, our list is for items in 9075-2
T321-06 Routines view -- we omitted, our list is for items in 9075-2
T321-07 Parameters view -- we omitted, our list is for items in 9075-2

Also there are a few non-core features that we support or partly support,
e.g. T213 INSTEAD OF triggers, T241 START TRANSACTION, T271 Savepoints.
There might be more.

**Comment by pgulutzan** [comment]
I fixed the two items in the table that I mentioned above as "my mistake". I see that K. Yukhin has been asked whether further extensions should take place, in one way or another.

**Comment by lenkis** [comment]
@kyukhin please reply ^^

**Comment by kyukhin** [comment]
@pgulutzan can we create separate, extended table?

**Comment by pgulutzan** [comment]
@kyukhin: Yes. I gave my reasons for opposing this idea, but if you want it anyway, it's not hard to make a series of tests that Tarantool will fail. Perhaps you want this as a private list rather than as a part of public documentation? Also, I can make detailed comments about what we could do for the failed tests in the current list of mandatory features.

**Comment by kyukhin** [comment]
I do not insist making it public. But having clear picture looks very attractive to me, especially when it commented properly.

**Comment by pgulutzan** [comment]
I wrote to @lenkis and @kyukhin on 2020-05-29 with an estimate of how long this could take, and am waiting for approval.

**Comment by Totktonada** [comment]
NB: The [link](https://www.tarantool.io/en/doc/2.2/book/sql/) from the original Timur's report gives me 404 now.

CC @artembo.

**Comment by pgulutzan** [comment]
@tsafin: sorry, it's been decided that this won't be done.
