### ISSUE TITLE
Meaningful GA stats for tracking documentation success

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#1345]

**Comment by lenkis** [comment]
https://www.knowledgeowl.com/home/using-google-analytics

**Comment by artur-barsegyan** [comment]
My feedback:

1. **Sessions and Users.** Not objective. It's not about the quality of the documentation. It's close to the size of the community. 
2. **Pages/Session**. It will look strange as a separate metric. Because the general pages/session metric will be the same month by month. Actually, we have 3,6 pages/session for the last half-year. And it almost the same.
3. Can try to add one of this feature at the site. Need to think.

In general, we can take the second one and divide it on some separates metrics for separate scenarios:
- find to drop_index
- find to replication
- etc

**Comment by lenkis** [comment]
Okay, let's try the scenario-centric approach. I'll ask our core + solution teams to come up with most typical scenarios.
