### ISSUE TITLE
socket.lua methods implementing LuaSocket API are not documented

### ISSUE THREAD

**Issue by igormunkin** [tarantool/doc#1363]
[`settimeout`](https://github.com/tarantool/tarantool/blob/master/src/lua/socket.lua#L1322) method was introduced in scope of tarantool/tarantool@bb6170e4 (lua socket: add basic [LuaSocket](http://w3.impa.br/~diego/software/luasocket/tcp.html) emulation), but there is still not a word about it in our docs. I also see other LuaSocket-like methods are also missing in our docs.

**Comment by pgulutzan** [comment]
Issue#2727 "luasocket wrapper" was added in 1.7.6,
for emulating LuaSocket in order to support some LuaRocks packages.
It is my understanding that the additional names were redundant,
not an API that we want to recommend to our users.
Our manual describes the "preferred" Tarantool way to specify timeout,
as part of socket.tcp_connect().

However, I added a short section that describes LuaSocket and
points to their manual, then put an example of settimeout()
with the LuaSocket API.

Incidentally I noticed a slight behaviour change in another example,
"Use of a TCP socket over the Internet". The example said:
"
tarantool> sock:error()
---
- null
...
"
I changed to:
"
tarantool> sock:error()
---
- Success
...
"
The API methods also work in Tarantool 1.10, so if
somebody wants the same changes elsewhere, just change the label
of this issue from "2.4" to an earlier version and re-open it.

**Comment by Totktonada** [comment]
I think it would be good if it will also land into earlier versions down to 1.10, because this functionality is present in those versions in fact.

I also think that it would be great if we'll have a list of luasocket emulation functions and methods we implement to make it obvious what is native API and what is for luasocket support. Just list, without descriptions.

**Comment by Totktonada** [comment]
@lenkis I changed the label to 1.10. Hope you don't mind.

**Comment by pgulutzan** [comment]
Okay. I see that the commit comment says
"Emulate http://w3.impa.br/~diego/software/luasocket/tcp.html API"
so there was never an intention to emulate other things like
http://w3.impa.br/~diego/software/luasocket/udp.html.
I also see that
http://w3.impa.br/~diego/software/luasocket/tcp.html API
mentions 
accept, bind, close, connect, getpeername, getsockname, getstats,
receive, send, setoption, setstats, settimeout, shutdown.
But some of those, for example setstats, are not mentioned
in the patch.
And some of those are already in the main part of the "Module socket" section
because the names are not LuaSocket-specific: accept, bind, close, send, shutdown.
So I suggest adding, at the end of the first sentence in the
LuaSocket wrapper functions section:
"as well as getpeername, getsockname, setoption, settimeout."

**Comment by Totktonada** [comment]
Cited the mentioned sentence:

> The LuaSocket API has functions that are equivalent to the ones described above, with different names and parameters, for example `connect()` rather than `tcp_connect()`.

It seems there are equivalents for `getpeername()` (`peer()`), `getsockname()` (`name()`), `setoption()` (`setsockopt()`) and for `settimeout()` (per-method `timeout` parameters). So it would be correct.

**Comment by pgulutzan** [comment]
I guess that means that we agree. I will copy what I suggested to all versions and close.
