### ISSUE TITLE
[6pt] mopinion: Fix path to json-path

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/doc#1563]
https://app.mopinion.com/dashboard/inbox/detail/3215722

Доку по json-path индексам ужасно сложно найти. Настолько сложно, что на stackoverflow есть специальная инструкция как искать. Так быть не должно

https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_space/#lua-function.space_object.create_index

**Comment by Onvember** [comment]
The information about JSON-path indexes appears in 2.2. And there are 2 notes about creating json-path indexes and 3 other useful notes ("Allowing null for an indexed key", "Using field names instead of field numbers", "Making a functional index with space_object:create_index()") in the `create_index` description.

So I have 2 suggestions on this issue:
1) Extract notes about json indexes into their own subsection "Creating indexes via JSON-path" and also add other notes about creating indexes to the table of contents on this page for easier finding.

2) Since 2.3 we have the [page](https://www.tarantool.io/en/doc/2.3/reference/reference_lua/json_paths/) describing updates via JSON-paths. We can change its name to "JSON indexes" and add the relevant info from `create_index` reference. And, of course, mention this page in `space` reference.

@artur-barsegyan @lenkis what do you think?
