### ISSUE TITLE
Update news on the web site

### ISSUE THREAD

**Issue by kostja** [tarantool/doc#167]
Update the news section on the web site with more recent releases.

**Comment by lenkis** [comment]
You mean "add newer publications to Media", right?

We have the following publications since Nov 17, 2016. Please choose which of them to add -- and which of the currently listed ones to remove:

- [ ] Feb 21 2017 How Tarantool works with memory (http://kostja.github.io/misc/2017/02/17/tarantool-memory.html)
- [ ] Feb 20 2017 Mail.Ru Group, IBS and Mellanox Announce Private Cloud Solution Based on Tarantool DBMS (https://corp.mail.ru/en/press/releases/9883/)
- [ ] Feb 15 2017 Tarantool IIoT, DBMS for Industrial Internet of Things, Released (https://corp.mail.ru/en/press/releases/9876/)
- [ ] Feb 13, 2017 Tarantool: the Good, the Bad and the Ugly (https://medium.com/@Vadim.Popov/tarantool-the-good-the-bad-and-the-ugly-1be5c5e04dd3#.vdh0fonty)
- [ ] Feb 03, 2017 Engineering Principles of Tarantool (http://kostja.github.io/misc/2017/02/03/tarantool-engineering-principles.html)
- [ ] Feb 01, 2017 Design Principles of Tarantool (http://kostja.github.io/misc/2017/01/24/tarantool-design-principles.html)
- [ ] Jan 23, 2017 Tarantool Data Virtualization (https://drive.google.com/file/d/0B7QYuyzuNQmfRl94UXRkZWJUVEk/view)
- [ ] Jan 20, 2017 Tarantool - technological view (https://goo.gl/3ZV70y)
- [ ] Jan 16, 2017 Master-Master Replication and Scaling of an Application between Each of the IoT Devices and the Cloud (http://highscalability.com/blog/2017/1/23/master-master-replication-and-scaling-of-an-application-betw.html?SSLoginOk=true)
- [ ] Jan 10, 2017 Switching from Tarantool 1.5 to Tarantool 1.6 (https://team.mail.ru/switching-from-tarantool-1-5-to-tarantool-1-6/)
- [ ] Jan 02, 2017 Efficient storage: how we went down from 50 PB to 32 PB (http://highscalability.com/blog/2017/1/2/efficient-storage-how-we-went-down-from-50-pb-to-32-pb.html)
- [ ] Dec 20, 2016 When and why I use an in-memory database or a traditional database management system (https://medium.com/@denisanikin/when-and-why-i-use-an-in-memory-database-or-a-traditional-database-management-system-5737f6d406b5#.x0zi2asdz)
