### ISSUE TITLE
Legalize Arch Linux support anyhow

### ISSUE THREAD

**Issue by tsafin** [tarantool/doc#1728]
There is nice, bleeding edge Tarantool package support on Arch Linux https://archlinux.org/packages/?q=tarantool (at the moment of writing it's the sole Linux which has 2.7.0 package at their repos). 

We should somehow legalize this community-driven package on our site, and provide appropriate references to community landing pages. i.e.
Create page named "Community-supported packages:"
- with Arch Linux and supported Tarantool version there

**Comment by Totktonada** [comment]
> (at the moment of writing it's the sole Linux which has 2.7.0 package at their repos).

I want to highlight that it is not quite good to push `x.y.0` versions to Linux distributions. Tarantool version that is tagged as `x.y.0` is not a real release. We can name it as alpha release within the `x.y` release series, but in fact it is just starting point of a new release series. Consider the [documentation](https://www.tarantool.io/en/doc/latest/dev_guide/release_management/) regarding our release policy. See also the relevant [note](https://github.com/Homebrew/homebrew-core/pull/64932#issuecomment-731320622) in homebrew-core.

AFAIK, @anatol maintains the tarantool package is Arch, so I'll mention him to share this information.

**Comment by pgulutzan** [comment]
I had no trouble saying "pacman -S tarantool", and building from source is straightforward. But, since it is community-driven and not officially supported, I guess that we only need to mention and provide a link, without instructions. I wonder whether it would be good enough to add a section in awesome-tarantool, something like the already-existing section
https://github.com/tarantool/awesome-tarantool#connectors
with title = "Community-supported unofficial Linux distros"? If so, somebody must declare it is "curated".

**Comment by Totktonada** [comment]
If I would be a user, I would search information how to install tarantool on my Linux distribution on the download page on the website. Even if we don't support certain distribution ourself and it is community driven, it would be good to list it on the website for users' convenience.

The similar situation with Gentoo Linux: I maintain 'tarantool' overlay with relevant ebuilds. Strictly saying, it is not community-driven, because I'm paid employee, but it is more like my personal effort.

**Comment by tsafin** [comment]
> I wonder whether it would be good enough to add a section in awesome-tarantool, something like the already-existing section
> https://github.com/tarantool/awesome-tarantool#connectors
> with title = "Community-supported unofficial Linux distros"? If so, somebody must declare it is "curated".

Yes, that would be a good start, the 2nd step would be to add reference to either "awesome-tarantool" or community-driven repo (or both) to the tarantool site, increasing discoverability of an existing solution.

The idea is - there should be easier way to find community solutions (certainly, given clear notice that they are unofficial and yada-yada).

**Comment by pgulutzan** [comment]
Re "the 2nd step": I added reference to awesome-tarantool 11 days ago and closed gh-1684. The change has not yet appeared in https://www.tarantool.io/en/doc/latest/contributing/contributing/.

**Comment by pgulutzan** [comment]
So my proposal is to add a section in awesome-tarantool:
"
Community-supported unofficial Linux distros

Arch  https://archlinux.org/packages/?q=tarantool
Gentoo https://github.com/tarantool/gentoo-overlay
"

but I admit that this might turn out to be a bad idea -- we might get complaints "why did you add this but not that?", or pressure to make what our contribution guide calls a "laundry list". Also, I am not sure what @Totktonada means when he says "list it on the website" -- does he mean this website, or somewhere else? Also, I am not sure what @tsafin means when he says "the tarantool site" -- does he mean somewhere in tarantool.io, for example https://www.tarantool.io/en/download, when one clicks "Other OS"?

So perhaps somebody will comment with an alternative proposal.

**Comment by Totktonada** [comment]
To be honest, I don't see any relation between the tarantool-awesome list and the list of supported Linux distributions (supported in some way, okay).

The list on the website is https://www.tarantool.io/en/download/ . A user read this section when (s)he want to install tarantool. If a distro is not listed here, then the user will consider it as unsupported (at all).

Is there any reason why not to add more installation instructions to the webpage we already have on the website? We can mark community driven packages with a note to highlight who is responsible person, but what is important: all those instructions  will be in one place and will not spread across different web resources.

> Arch https://archlinux.org/packages/?q=tarantool
> Gentoo https://github.com/tarantool/gentoo-overlay

What a user supposed to do with an url? We should add an *instruction* how to enable a repository on given distro.

**Comment by pgulutzan** [comment]
I asked tsafin already whether tarantool.io/en/download would be acceptable.
This page is not part of the manual.
The manual starts by recommending "Using a Docker image"
https://www.tarantool.io/en/doc/latest/getting_started/getting_started_db/
and later says
"For production purposes, we recommend to install Tarantool via official package manager."
and points to tarantool.org/download.html. But if you click that you get to
https://www.tarantool.io/en/download/os-installation/docker-hub/
... I don't know why we like Docker so much.

By the way there is a link error on this page.
If you click "More details" you get to
https://www.tarantool.io/ru/product/enterprise/
... I don't know why we like to point to "ru" rather than "en" here.

Anyway, if a lucky user finds the "Other OS" button and clicks it,
we list: Mac OS, Docker Hub, Ubuntu, Debian, Fedora, RHEL/CentOS,
Amazon Linux, FreeBSD, Building from source code.

We could add to the list: "Unofficial OS".
And if somebody clicks that, they could see:

Unofficial OS
The following Linux distros are not officially supported by Tarantool.
However, they have been examined by Tarantool development staff members
who approve them. Click for the instructions supplied by package managers.
Arch  https://archlinux.org/packages/?q=tarantool
Gentoo https://github.com/tarantool/gentoo-overlay

However, I believe it would be an error if we wrote the instructions,
instead of pointing to the package managers.
It should be their responsibility.
And I worry that our instructions would eventually look obsolete.
For example, our typical instructions for rpm look like:
curl -L https://tarantool.io/CYyVhK/release/2.5/installer.sh | bash
sudo yum install tarantool
... I don't know why we like yum so much.

**Comment by igormunkin** [comment]
> Unofficial OS
The following Linux distros are not officially supported by Tarantool.

@pgulutzan, I personally believe that it's better to name this section "Community driven repositories" with the links you mentioned rather than "Unofficial OS".

**Comment by tsafin** [comment]
1. On one hand I do see value in having list of known operating systems packages at the tarantool/awesome-tarantool list. It's easy to maintain and might include externally supported items;
2. On the other hand I'd rather see information about community supported OS targets on our own tarantool.io site. 

Apparently, the 2nd approach might be less flexible, than 1st one, but, in a longer term, they both could complement each other.

**Comment by pgulutzan** [comment]
Okay, I guess we can agree that the words "Community-driven repositories" are better than "Unofficial OS" (I only got that idea because elsewhere we say "official OS").
Maybe most of us can agree that all we want is to give directions to find the products.
Maybe we cannot agree to use awesome-tarantool.
As for tarantool.io/en/download, I cannot change it. Perhaps @veod32 can.

**Comment by NickVolynkin** [comment]
We don't officially support Arch distributions, and I don't think we should do this in our work time. If there's an Arch enthusiast willing to update docs about Tarantool on Arch, they're welcome to contribute.

**Comment by Totktonada** [comment]
Download instructions are in the closed source repository, so it is impossible to update them for the outside person. But okay, I have all necessary accesses, and I'll do.

The external enthusiast (@anatol) already did all work. We just need to add a simple command (`pacman -Sy tarantool`) to our website. I don't understand why it is so hard.

**Comment by patiencedaur** [comment]
> Download instructions are in the closed source repository

This repository is not tarantool/doc, and the task is outside the scope of the Tarantool doc team responsibilities (at least for now). Closing.
