### ISSUE TITLE
Auto-detect the user operating system on the download page

### ISSUE THREAD

**Issue by kostja** [tarantool/doc#182]
The tab corresponding to the detected operating system must be moved to the top and auto-open.

**Comment by bigbes** [comment]
In case, when OS is one of the listed (https://tarantool.org/download.html), we need to move it's tab to the top and open it.
If it's Windows or other OS not listed in the list (but it supports Docker), then we'll open Docker (as it's first in the list).
Otherwise do nothing.

Before:
<img src="https://cloud.githubusercontent.com/assets/495636/24659546/aa482ec8-1955-11e7-9027-46b091efd0e8.png" width="500"></img>

After:
<img src="https://cloud.githubusercontent.com/assets/495636/24659564/b43aa1fe-1955-11e7-8b14-b5e514fcb41f.png" width="500"></img>

**Comment by kostja** [comment]
Done.
