### ISSUE TITLE
[3pt] Team guide: localization workflow

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/doc#1885]
# Tell about our workflow with localization

**Reviewer:** @

# DoD

- [x] how to prepare a document for localization: proofread, fix markup, break huge paragraphs.
- [x] how to do a good review; what's the meaning and purpose of review

**Comment by patiencedaur** [comment]
Fixed with these documents:
[Tarantool language and style guidelines](https://www.tarantool.io/en/doc/latest/contributing/docs/style/)
(Internal) [Translation-related guidelines](https://www.notion.so/tarantool/d61bf0f152814555b0e105d77d2f6790)
(Internal) [Translator and translation reviewer objectives](https://www.notion.so/tarantool/5e374a21775d4ee69494f79ebe933844)
