### ISSUE TITLE
[2pt] Implement on_shutdown API

### ISSUE THREAD

**Issue by Totktonada** [tarantool/doc#2104]
It seems, @TarantoolBot missed this commit: https://github.com/tarantool/tarantool/commit/3010f024ea2378ff776ee773dc88cd53871b9a42 (at least I don't see an issue with such title in the issue tracker).

## Details

Implemented on_shutdown API, which allows to register functions
that will be called when the tarantool stopped. Functions will
be called in the reverse order they are registered. So the module
developer registers one fuction that starts module termination and
waits for its competition. This function should be fast or used an
asynchronous waiting mechanism (coio_wait or cord_cojoin for example).

**root document:** https://www.tarantool.io/ru/doc/latest/dev_guide/reference_capi/

**SME:** @ Korablev77

**Comment by NickVolynkin** [comment]
@Totktonada thanks!

**Comment by pgulutzan** [comment]
@Totktonada:

I'm not sure if you care about spelling in comments, but
I noticed in module.h that the new box_on_shutdown
comments have two errors just before
API_EXPORT int
box_on_shutdown(void *arg, int (*new_hadler)(void *),
		int (*old_handler)(void *));
...
"othrewise" should be "otherwise"
"hadler" should be "handler"

Anyway, this new module.h is present if I remember to add a recent repository as in
https://www.tarantool.io/en/download/os-installation/ubuntu/
(I wonder whether I failed to explain that adequately in the tutorial).
However, in the C API tutorial, the instructions for typical situations are
https://www.tarantool.io/en/doc/latest/tutorials/c_tutorial/).
export CPATH=/usr/local/include/tarantool:/usr/local/include/msgpuck
gcc -shared -o easy.so -fPIC easy.c
and now that fails because "trivia/util.h" is missing.
Is it my fault or is it your fault?

Ignoring that, I can add something based on this issue's description,
which (I believe) is just a matter of saying it in different English:

box_on_shutdown(void *arg, int (*new_handler)(void *),
		int (*old_handler)(void *))

The box_on_shutdown function lets users register functions
that will be called when the Tarantool instance stops. Such functions will
be called in the reverse order that they are registered (last-registered = first-called). So the module
developer typically would one function that starts module termination and
waits for its completion. This function should be fast or should use an
asynchronous waiting mechanism (for example coio_wait or cord_cojoin).

By the way coio_wait is documented for the C API
https://www.tarantool.io/en/doc/latest/dev_guide/reference_capi/coio/
but cord_cojoin is not, so I will not include :ref: here.

It will be a new .rst file in dev_guide/reference_capi

**Comment by Totktonada** [comment]
> I'm not sure if you care about spelling in comments, but
> I noticed in module.h that the new box_on_shutdown
> comments have two errors just before
> API_EXPORT int
> box_on_shutdown(void *arg, int (*new_hadler)(void *),
> int (*old_handler)(void *));
> ...
> "othrewise" should be "otherwise"
> "hadler" should be "handler"

I would appreciate if you'll open a PR with fixes. The src/module.h file is generated, the actual source file is src/on_shutdown.h.

There are plans to generate the C API documentation from those comments in a future (https://github.com/tarantool/doc/issues/1611#issuecomment-769719963).

> Anyway, this new module.h is present if I remember to add a recent repository as in
> https://www.tarantool.io/en/download/os-installation/ubuntu/
> (I wonder whether I failed to explain that adequately in the tutorial).
> However, in the C API tutorial, the instructions for typical situations are
> https://www.tarantool.io/en/doc/latest/tutorials/c_tutorial/).
> export CPATH=/usr/local/include/tarantool:/usr/local/include/msgpuck
> gcc -shared -o easy.so -fPIC easy.c
> and now that fails because "trivia/util.h" is missing.
> Is it my fault or is it your fault?

Neither module.h, nor msgpuck.h include trivia/util.h (it is the internal tarantool header). There was an [error](https://github.com/tarantool/small/commit/9ee874c2df7e60c388d49d1d6851950477b40c3f) of this kind in small, but the tutorial does not mention the small library (and it is anyway error at building libsmall itself). It seems, it is some problem in your local setup, but I unable to diagnose better with given information. Can you share the full error message?

Everything about the new trigger is to @EvgenyMekhanik and @Korablev77, I don't have the necessary context here.

**Comment by pgulutzan** [comment]
@Totktonada:
Re the spelling errors: I listed them and a few more, in Spelling errors in module.h Issue#6061.
Re trivia/util.h: It was my fault, I apologize.
Re the text: I incorrectly guessed that you were involved because you filed the issue. I will wait for others.

**Comment by pgulutzan** [comment]
There was no comment from others so I submitted a pull request and assigned reviewer = @NickVolynkin.
