### ISSUE TITLE
[8pt] New SQL data types and function changes

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/doc#2516]
The new data types in SQL -- MAP, ARRAY, ANY -- should be done together because they affect the same charts and subsections of the SQL Reference. Also there might be an effect on SQL functions so the tentative plan is to work on those at the same time if all the changes are in the same .rst file.
Thus fixing this issue may be fixing:
Issue #2406 Literals for INTEGER, DECIMAL and DOUBLE
Issue #2439 SUBSTR() function
Issue #2440 Field type ANY in SQL
Issue #2455 Default types of SQL built-in functions
Issue #2461 Field type ARRAY in SQL
Issue #2462 Field type MAP in SQL
Issue #2475 Syntax for ARRAY in SQL

**Comment by patiencedaur** [comment]
Dear Peter @pgulutzan,

I am now the Tarantool documentation team lead instead of @NickVolynkin.

Once you're finished working on an issue, please tag me in a comment to the PR so I know that the task is ready. Then we can review it and pass it to the translation team.

It's best if you do it for smaller chunks of work rather than large ones. For example, you described this issue as an epic overarching several other issues. In this case, tag me when you're finished with each smaller issue, not with the whole epic. This will simplify and accelerate our work.

Thank you!

P. S. We're going to update our style guide, making it more detailed. Just keeping you informed. I'll send you a link once it's finished. Here's the work in progress if you're interested: https://github.com/tarantool/doc/pull/2539.

**Comment by patiencedaur** [comment]
@pgulutzan
Yes, please add me to the reviewer list. Here is my work email, which you can CC the reports to: d.daur@corp.mail.ru.

I understand that this epic is about making small changes to many documents. So you're right---it would be best if you notify when the whole thing is done.

How do you usually get the next assignment to work on---should I just assign issues to you so you pick them up?

**Comment by pgulutzan** [comment]
Thanks for understanding. You've probably noticed that I used to be involved with all documentation (because K. Osipov hired me first), but nowadays I only get a few assignments related to internals or (especially) to SQL. Sometimes I self-assign what looks interesting, and always I look for flaws; you can check with the developers that I've bothered recently (e.g. M. Imeev, M. Siomkin, T. Safin, A. Turenko) and they can tell you whether they have any problems with this. And yes you can assign issues to me whenever you wish.

**Comment by patiencedaur** [comment]
Thank you, Peter. We will definitely have something about SQL to document quite soon.

Here are the style guide updates, as promised:
https://www.tarantool.io/en/doc/latest/contributing/docs/style/

**Comment by patiencedaur** [comment]
Related issue: https://github.com/tarantool/doc/issues/2797
