### ISSUE TITLE
[2pt] Think about using the pronoun 'we' to the reader in "Getting Started"

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/doc#2520]
Есть точка зрения, что подаче материала в Getting Started некорректна:
-  использование местоимения 'we', кажется неправильным. Есть мнение, что в индустрии так не пишут.
-  в тексте туториала местами используется 'you'/'we'. Это может сбивать с толку

Предлагаю в рамках этого тикета посмотреть на другие технологии и их туториаоы. Нужно понять: как в других продуктах пишут подобные разделы и соотнести с нашим текущим текстом.

**Reviewer:** @patiencedaur 

## Definition of done

- [ ] Предложен список туториалов известных технологий на основе которых описана критика к нашему тексту. Если есть расхождения

**Comment by NeraverinTarantool** [comment]
Примеры Getting started

- https://www.postgresqltutorial.com/postgresql-getting-started/
- https://docs.mongodb.com/manual/tutorial/getting-started/
- https://docs.microsoft.com/en-us/sql/relational-databases/tutorial-getting-started-with-the-database-engine?view=sql-server-ver15

**Comment by Totktonada** [comment]
I suggest to look at those recommendations (and follow links inside): https://wiki.gentoo.org/wiki/Gentoo_Wiki:Guidelines#Avoid_first_and_second_person_writing.

**Comment by patiencedaur** [comment]
I would vote for using "we" only in beginner articles like the [Getting started guide](https://www.tarantool.io/en/doc/latest/getting_started/), to lower the entry level. After all, "we" sounds friendly, and Tarantool is a very complex tool.
Still, I won't use the first-person pronoun too often even in this case: it's not clear who "we" are in this context.

Since Tarantool has recently been turning to B2B rather than to B2C audience, and since EE is increasingly important, it seems only logical that people would want the docs more formal.

I'm adding more writing instructions in #2539. This looks like a related issue.

**Comment by patiencedaur** [comment]
Resolved in https://github.com/tarantool/doc/pull/2539
