### ISSUE TITLE
Update the Transactions section

### ISSUE THREAD

**Issue by rindblack15** [tarantool/doc#2906]
**Related dev. issue(s):** 

**Product:** Tarantool
**Since:** 2.10
**Root document:** https://www.tarantool.io/en/doc/latest/book/box/atomic/
**SME:** @ Mons

# Details

Use the material to restructure and rewrite the transaction section to better suit the user's needs.

# Definition of done

- [ ] The structure of the transaction section has been changed.
- [ ] The information has been updated.

Related with https://github.com/tarantool/doc/issues/2812, https://github.com/tarantool/doc/issues/2793.

**Comment by patiencedaur** [comment]
Consider including the content of the first-level "Streams" section in the new "Transactions" section.
The original decision to put streams on the first level was was based on a marketing premise, because streams were a key feature of the 2.10.0.beta2 release. Now the hype is gone, and we can safely put this content among the other transaction-related information where it belongs.
