### ISSUE TITLE
Document ADD CONSTRAINT statement

### ISSUE THREAD

**Issue by Gerold103** [tarantool/doc#592]
@Korablev77 please, write here a description.

**Comment by Korablev77** [comment]
We have added new `ALTER TABLE` clauses: `ADD CONSTRAINT` and `DROP CONSTRAINT`. According to ANSI syntax is following:

```
ALTER TABLE <referencing table> ADD CONSTRAINT
  <referential constraint name> FOREIGN KEY
  <left paren> <referencing columns> <right paren> REFERENCES
  <referenced table> [ <referenced columns> ] [ MATCH <match type> ]
  [ <referential triggered action> ] [ <constraint check time> ]

<match type> ::= FULL | PARTIAL | SIMPLE
<referential triggered action> ::= ON DELETE <action> | ON INSERT <action> | ON UPDATE <action>
<action> ::= NO ACTION | CASCADE | RESTRICT | SET NULL | SET DEFAULT
<constraint check time> ::= NOT DEFERRABLE deferred_opt | DEFERRABLE deferred_opt
<deferred_opt> ::= INITIALLY DEFERRED | INITIALLY IMMEDIATE
```

`ALTER TABLE <referencing table> DROP CONSTRAINT <constrain name>`

In our terms it looks like:

```
ALTER TABLE t1 ADD CONSTRAINT f1 FOREIGN KEY(id, a) REFERENCES t2 (id, b) MATCH FULL;
ALTER TABLE t1 DROP CONSTRAINT f1;
```
Now the only constraint user may add is `FOREIGN KEY` constraint. After FK constraint is created, each new (inserted or updated) entry in child table is checked on presence in parent table ('parent' table is referenced table and 'child' table is referencing table). In case there is no corresponding entry in parent table, error is raised. Currently,` MATCH` clause doesn't affect FK checking in any way (see https://github.com/tarantool/tarantool/issues/3455). Other features such as triggered action or check time work the same as in SQLite. Also, there is list of requirements to create FK constraint:
- referenced table must exist;
- foreign key constraint can be created only if child space is empty;
- parent space must feature UNIQUE index which consists exactly from referenced columns (but order may differ). If there are several indexes which satisfy this requirement, random one is choosen;
- types of referencing and referenced columns must be comparable;
- collations of referencing and referenced columns must match;
- referenced column list mustn't comprise duplicates;
- referenced table can't be VIEW;

It is worth mentioning that table can't be dropped until other tables reference it. Moreover, implicitly referenced index of parent table (that one from requirements list) can't be dropped as well. `DROP TABLE` statement and space:drop() function drop all child FK constraints.

Note that user still can create FK constraint as a part of `CREATE TABLE` statement, but referenced table must exist (except for self-referencing constraints - they are allowed). This is the main difference between our FK constraints and SQLite ones. And it is the reason why we decided to implement separate `ADD CONSTRAINT` statement - in order to resolve cyclic FK dependencies.

**Comment by lenkis** [comment]
Peter, please add this to the SQL tutorial in tarantool/doc + to the SQL manual at google docs.

**Comment by pgulutzan** [comment]
This clause was already added to the SQL manual about two weeks ago. I see that other details about foreign keys, such as on update|delete clauses, aren't mentioned yet but that's a separate matter. I added an ALTER TABLE example to the tutorial.
