### ISSUE TITLE
Verify support for SQL:2016 features

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#690]
This list requires a review: https://tarantool.io/en/doc/2.1/book/sql/

**Comment by lenkis** [comment]
@kostja please clarify your requirements for this task and assign to Peter.

**Comment by pgulutzan** [comment]
I sent a review to E. Shebunyaeva + K. Yukhin + N. Pettik.

**Comment by pgulutzan** [comment]
@veod32: FYI, This is the review that I sent on 2020-11-09 to @lenkis  + @kyukhin + @Korablev77.

Hi,

This issue https://github.com/tarantool/doc/issues/690
was about what is now the Tarantool 2.6 "SQL Features" section
https://www.tarantool.io/en/doc/latest/reference/reference_sql/sql-features/
You wrote
"This list requires a review ... @kostja please clarify your
requirements for this task (what exactly you want to audit
there + how to report the result) and assign to Peter."
He did not reply so I self-assigned and this is the review.

No change needed for version 2.5.

It is possible that we will change the list
for version 2.6 / 2.7 for these details:

E021-01 Character data type (including all its spellings)
Issue#3665 sql: introduce strings with fixed length type -- will help.
wishlist

E021-02 CHARACTER VARYING data type (including all its spellings)
Issue#4088 Implement VARCHAR data type -- will help.
wishlist

E011-02 REAL, DOUBLE PRECISION, and FLOAT data types
The long "Note" about migrating from 2.1 to 2.2 is obsolete.

E011-03 DECIMAL and NUMERIC data types
Issue#4415 "Implement DECIMAL data type" -- will help.
wishlist but in progress.

E121-04 OPEN statement etc.
Issue#3082 Support iterators over SQL query result -- will help.
wishlist

F031-03 GRANT statement
Issue#2243 Support GRANT and REVOKE -- will help.
wishlist

F031-04 ALTER TABLE statement: add column
Issue#3075 Enable addition of new columns in ALTER -- will help.
wishlist but in progress.

F031-13 DROP TABLE statement: RESTRICT clause
Issue#3491 sql: implement CASCADE specifier for DROP TABLE -- will not help.

F031-16 DROP VIEW statement: RESTRICT clause
Issue#2355 SQL: DROP VIEW [RESTRICT|CASCADE] -- would have helped.
K. Yukhin closed this saying it is superseded but that may be wrong.

F051 Basic date and time
Issue#4898 Restore datetime functions in SQL -- will not help.
Issue#3694 sql: introduce conventional DATE and TIME types -- will help.
wishlist

I will let issue#690 be 'open' and change when these items get fixed.

Peter Gulutzan

**Comment by patiencedaur** [comment]
@pgulutzan You closed this by https://github.com/tarantool/doc/pull/2350, is that correct?

**Comment by pgulutzan** [comment]
@patiencedaur 
Not due to issue 2350, but I think this can be closed, if you approve.

In the initial note for issue 2350 I mentioned only a small change to the list.

Obviously we don't expect K. Osipov or E. Shebunyaeva to reply to the email, 

The matters that I described then are still approximately true, except ...

E011-03 DECIMAL and NUMERIC data types
This is changing due to issue 2516
see https://github.com/tarantool/doc/pull/2523/commits/a070ccec6cdaf6e00eb6df36d1a3b8cd0a62c61c

E011-06 Implicit casting among the numeric data types:
We had to change the definition, i.e. NUMBER is not a numeric data type.

F031-04 ALTER TABLE statement: add column
This is now possible in limited circumstances, and the description was changed.

F051 Basic date and time (and subheadings)
The issue number has changed, now it is 6773, I see that you are aware of it.
