### ISSUE TITLE
fiber.join() return value description is VERY incomplete

### ISSUE THREAD

**Issue by denesterov** [tarantool/doc#717]
https://tarantool.io/en/doc/1.10/reference/reference_lua/fiber/#fiber-object-join

Has very defaulty return value description:

"Return:
true if successful, false if not successful"

In fact, fiber.join() first return value contains boolean describing fiber termination conditions:

* true, if it has terminated normally with return. Then second return value contains return value itself
* false, if fiber was terminated abnormally. Then second return value contains crash description (as string? please double-check)

sample:

local ok, result = f:join()
if ok then
  print('Fiber returned '..tostring(result))
else
  print('Fiber crashed at '..tostring(result))
end

ALSO, One important note: One can join() already stopped (returned, or crashed) fiber. And above result values will work ok in this situation.

**Comment by pgulutzan** [comment]
I don't understand what is being said here about "crash".
I changed Tarantool source so that box.info() would cause a segmentation fault.
I changed the fiber function so it would call box.info().
"
fiber=require('fiber')
function fu2() fiber.sleep(5) box.info() return 'w' end
fi2=fiber.new(fu2) fi2:set_joinable(true)
fiber.status(fi2)
ok, result = fi2:join()
if ok then print('Fiber returned ' .. tostring(result))
else print('Fiber crashed at ' .. tostring(result)) end
"
Result = server stops without printing "Fiber crashed at ..." etc.
Perhaps we have different ideas about what "crash" means.

**Comment by denesterov** [comment]
I dont expect fiber to recover segfaults. Crash = e.g. referencing a nil value etc, a Lua crash

**Comment by pgulutzan** [comment]
Okay, from your words "referencing a nil value" I can see what you mean ...
"
b = nil
fiber=require('fiber')
function fu2() fiber.sleep(5) b:setRotation(45) end
fi2=fiber.new(fu2) fi2:set_joinable(true)
a, b = fi2:join()
a
b:upack()
fi2.status()
"

The result is a boolean and a "struct error".
Thanks for noticing.
