### ISSUE TITLE
Not clear how to remove sequence from index

### ISSUE THREAD

**Issue by knazarov** [tarantool/doc#723]
I was trying to find a way to remove a sequence from index. Apparently it is done like this:

```lua
index:alter({sequence=false})
```

Why `false`? This is not documented as of now. Also probably the modification of other index options is not documented as well.

**Comment by pgulutzan** [comment]
Actually the modification of other index options is documented, but instead of listing them all we simply say ""options list, same as the options list for create_index, see the chart named Options for space_object:create_index()." Then there are a few sentences of explanation and some examples, as usual.
