### ISSUE TITLE
Revise errors thrown by box functions

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#724]
Please revise error descriptions in reference on standard `box` functions (at least for `box.space`, `box.index`, `box.session`):

1. Double-check return vs throw.

E.g. for `space:insert()` we say:
```
Possible errors: If a tuple with the same unique-key value already exists, returns ER_TUPLE_FOUND.
```
But it does not return, it rather throws the error.

2. Add missing errors.

E.g. `space:insert()` also throws  er_wal_io, er_memory_limit, er_vy_quota_timeout (for vinyl), er_read_only.

**Comment by pgulutzan** [comment]
I have changed many places where I mistakenly used the word "return" when "raise" or "throw" would be more appropriate.
With regard to "missing errors" -- have you considered the implications of this request? I believe that it could mean that every function would have a list of errors which is large, which contains redundancy since the error list is available, contains unnecessary guesses because some errors might never or almost never happen for a given function, and is subject to constant change because these things are thrown by even minor changes in source code (which generally I won't be aware of).

**Comment by pgulutzan** [comment]
@lenkis: This issue has existed for a long time. What do you think of my comment above (March 31)? May I close this?

**Comment by pgulutzan** [comment]
I am closing because there was no further discussion and I believe/hope that my commit has addressed the issue. If I am wrong, then of course it may be re-opened.
