### ISSUE TITLE
net.box#eval and net.box#call are lacking return value description and examples

### ISSUE THREAD

**Issue by akudiyar** [tarantool/doc#743]
Link: https://tarantool.io/ru/doc/1.10/reference/reference_lua/net_box/#lua-function.conn.eval

Also there is no description what is returned if an eval-ed string is called with array/stream input. In fact two arrays are returned, but the first array seems to be empty both in success and error cases.

**Comment by pgulutzan** [comment]
I changed the examples in conn:eval() and conn:call() so that, as well as showing the requests, the showed the responses to the requests. I included an example that has a complex argument. In the text part I explained that the returned value is what a function returns or what "return " + expression returns.
