### ISSUE TITLE
Document breaking changes in privileges

### ISSUE THREAD

**Issue by lenkis** [tarantool/doc#755]
- [ ] Bags of privileges are not documented. It is now possible to grant create/drop/alter on object type, e.g. grant ‘create any space’ privilege. You just omit the object name in grant/revoke statement. This is not in the docs.

- [ ] Besides, the docs do not mention alter privilege.

- [ ] Finally, they give very little information about create/drop privileges - no examples, just mention create/drop exists.

------

See https://github.com/tarantool/tarantool/issues/945:

New types of privileges were introduced. In order to create, drop or alter space or index, you should have a corresponding privilege. E.g.:
```
box.schema.user.create("optimizer", { password  = 'secret' })
box.schema.user.grant("optimizer", "alter", "space")
person = box.schema.space.create("person")
box.session.su("optimizer")
i = s:create_index("primary") -- success
s:insert{1} -- fail
s:select{} -- fail
s:drop() -- fail
```

Incompatible change in 2.1: Tarantool 1.10 requires read/write/execute privileges on an object to allow create, drop or alter. These privileges are no longer sufficient in 2.1. To remedy the problem Tarantool 2.1 automatically grants create/drop/alter privileges on an object if a user has read/write/execute privileges on it during schema upgrade. But old scripts may stop working if read/write/execute is granted after schema upgrade. Additionally, create/drop/alter privileges are already supported in 1.10, which also supports the old semantics of read/write/execute. You are encouraged to grant new privileges in 1.10 before upgrade and modify your scripts.

**Comment by pgulutzan** [comment]
I suggested via email on May 13 that this be closed.

**Comment by kyukhin** [comment]
Could you please clarify why you are going to close it? Request looks reasonable.

**Comment by Totktonada** [comment]
Any news?

**Comment by pgulutzan** [comment]
I forwarded to the email to the people who asked.

**Comment by pgulutzan** [comment]
There have been no replies to my emails about this since August 2018,
and no fixes for some issues related to privileges.
So I will document as if all is well.

I re-tested by running the Tarantool server as a console,
starting as admin, then granting to guest,
then saying box.session.su('guest'), then trying to create/drop etc.
A test like this depends on loadstring() working regardless of privileges.

On Friday I will make the following changes affecting authentication.rst
https://www.tarantool.io/en/doc/latest/book/box/authentication/#owners-and-privileges
and on similar sections for version 2.3 + version 2.4 (which I have not re-tested yet).

After the words "The following privileges can be granted: ...".
No change. The list does not include 
'reference' or 'trigger' or 'insert' or 'update' or 'delete'.
However, we should not document what nobody asked us to document.

Replace the words
"‘drop’, e.g. allow box.sequence.x:drop (currently this can be granted but has no effect)"
with
"'drop', e.g. allow box.sequence.x:drop (access to certain system spaces is also necessary)"

Replace the words
"To drop an object, users must be the object’s creator or be ‘admin’.
with
"To drop an object, users must be 'admin' or have the 'super' role.
Some objects may also be dropped by their creators."

Replace the words
"object-type is any of ‘space’, ‘index’, ‘sequence’, ‘function’, role-name, or ‘universe’;"
with
"object-type is any of ‘space’, ‘index’, ‘sequence’, ‘function’, 'user', 'role', or ‘universe’;"

After the words
"object-name is what the privilege is for (omitted or nil if object-type is ‘universe’);"
add
"(may be omitted or nil if the intent is to grant for all objects of the same type):"

After the words
"In these examples the object’s creator grants precisely the minimal privileges necessary for particular operations, to user ‘U’."
In fact some examples contain
"box.schema.user.grant('U','create','universe')"
which is not minimal. I will replace 'universe' with object-type.
Also, some examples assume that 'U' can grant things that only administrators should grant.
Also, some example situations are missing or requirements have apparently changed.
So I will replace the whole list with this ...

"
In these examples an administrator grants precisely
the minimal privileges necessary for particular operations,
to user 'U'.

.. code-block:: lua

    -- So that 'U' can create spaces:
      box.schema.user.grant('U','create','space')
      box.schema.user.grant('U','write', 'space', '_schema')
      box.schema.user.grant('U','write', 'space', '_space')
    -- So that 'U' can  create indexes on space T
      box.schema.user.grant('U','create,read','space','T')
      box.schema.user.grant('U','read,write','space','_space_sequence')
      box.schema.user.grant('U','write', 'space', '_index')
    -- So that 'U' can  alter indexes on space T (assuming 'U' did not create the index)
      box.schema.user.grant('U','alter','space','T')
      box.schema.user.grant('U','read','space','_space')
      box.schema.user.grant('U','read','space','_index')
      box.schema.user.grant('U','read','space','_space_sequence')
      box.schema.user.grant('U','write','space','_index')
   -- So that 'U' can alter indexes on space T (assuming 'U' created the index)
      box.schema.user.grant('U','read','space','_space_sequence')
      box.schema.user.grant('U','read,write','space','_index')
   -- So that 'U' can create users:
      box.schema.user.grant('U','create','user')
      box.schema.user.grant('U', 'read,write', 'space', '_user')
      box.schema.user.grant('U', 'write', 'space', '_priv')
   -- So that 'U' can create roles:
      box.schema.user.grant('U','create','role')
      box.schema.user.grant('U', 'read,write', 'space', '_user')
      box.schema.user.grant('U', 'write', 'space', '_priv')
    -- So that 'U' can create sequence generators:
      box.schema.user.grant('U','create','sequence')
      box.schema.user.grant('U', 'read,write', 'space', '_sequence')
    -- So that 'U' can create functions:
      box.schema.user.grant('U','create','function')
      box.schema.user.grant('U','read,write','space','_func')
    -- So that 'U' can create any object of any type
      box.schema.user.grant('guest','read,write,create','universe')
    -- So that 'U' can grant access on objects that 'U' created
      box.schema.user.grant('U','write','space','_priv')
    -- So that 'U' can select or get from a space named 'T'
      box.schema.user.grant('U','read','space','T')
    -- So that 'U' can update or insert or delete or truncate a space named 'T'
      box.schema.user.grant('U','write','space','T')
    -- So that 'U' can execute a function named 'F'
      box.schema.user.grant('U','execute','function','F')
    -- So that 'U' can use the "S:next()" function with a sequence named S
      box.schema.user.grant('U','read,write','sequence','S')
    -- So that 'U' can use the "S:set()" or "S:reset() function with a sequence named S
      box.schema.user.grant('U','write','sequence','S')
    -- So that 'U' can drop a sequence (assuming 'U' did not create it)
      box.schema.user.grant('U','drop','sequence')
      box.schema.user.grant('U','write','space','_sequence_data')
      box.schema.user.grant('U','write','space','_sequence')
    -- So that 'U' can drop a function (assuming 'U' did not create it)
      box.schema.user.grant('U','drop','function')
      box.schema.user.grant('U','write','space','_func')
    -- So that 'U' can drop a space that has an index but no associated grants
      box.schema.user.grant('U','create,drop','space')
      box.schema.user.grant('U','write','space','_schema')
      box.schema.user.grant('U','write','space','_space')
      box.schema.user.grant('U','write','space','_space_sequence')
      box.schema.user.grant('U','read','space','_trigger')
      box.schema.user.grant('U','read','space','_fk_constraint')
      box.schema.user.grant('U','read','space','_ck_constraint')
      box.schema.user.grant('U','read','space','_func_index')
   -- So that 'U' can drop any object of any type
      box.schema.user.grant('U','drop,read,write','space')
"

Also in box_space.rst the description of _priv will change.

**Comment by Totktonada** [comment]
Thank you!

I agree, it is better to have a documentation that is consistent with an implementation even if it is not easy to explain a current state. (Good implementation and docs in-sync are better, of course, but poor implementation and no docs is worse.)

Sorry, it didn't find any time to dive into the discussion you send me.

----

> After the words "The following privileges can be granted: ...".
> No change. The list does not include
> 'reference' or 'trigger' or 'insert' or 'update' or 'delete'.
> However, we should not document what nobody asked us to document.

From 2.6.0-136-g2711797be sources:

```c
enum priv_type {
        <...>
        /* REFERENCE - required by ANSI - not implemented */
        PRIV_REFERENCE = 256,
        /* TRIGGER - required by ANSI - not implemented */
        PRIV_TRIGGER = 512,
        /* INSERT - required by ANSI - not implemented */
        PRIV_INSERT = 1024,
        /* UPDATE - required by ANSI - not implemented */
        PRIV_UPDATE = 2048,
        /* DELETE - required by ANSI - not implemented */
        PRIV_DELETE = 4096,
        <...>
```

It seems, they're not implemented, so there is nothing to document now. You decision looks perfectly correct for me.
