### ISSUE TITLE
Minor version stability interpretation

### ISSUE THREAD

**Issue by parihaaraka** [tarantool/doc#778]
[here:](https://www.tarantool.io/en/download/os-installation/2.1/ubuntu/)
> Available versions: 1.10 (lts) 2.1 (stable)

"Release management" chapter says that 2.**1** means **beta**

**Comment by lenkis** [comment]
@kyukhin I'm confused, too. Let's discuss and make it clear in the manual.

**Comment by printercu** [comment]
Current status
- 1.10 - LTS
- 2.1 - stable
- 2.2 - beta
- 2.3 - alpha/master

Looks like it's like a rolling release: 2.2 will become stable soon.

**Comment by kyukhin** [comment]
We need to refactor this chapter of documentations.
Currently we use following scheme:
1. 1.10.x is declared LTS and will be supported nearest couple of years. Minor version is updated quarterly.
2. 2.X.Y means following
    - X denotes release serie. It is relatively short living, and there're only 2 stable releases before X is superseded by X+1
    - Y denotes status of serie. Codes are:
       * 0 - it is current master (trunk) and is not forked so far. This is where new features are landed
       * 1 - means  that serie is a beta version. It is not declared stable and no new features are comitted here
       * 2, 3 - are numbers denoting stable versions  which are tagged quarterly

Examples:
2.5.0 - current master
1.10.8 - LTS version (if 8 is max in 1.10 tag list), deprecated otherwise
2.3.2 - stable version of 2.3 serie (first)
2.2.3 - stable version of 2.2 serie (last)

**Comment by Onvember** [comment]
outdated
