### ISSUE TITLE
Enrich LuaJIT related docs with table.sort semantics

### ISSUE THREAD

**Issue by igormunkin** [tarantool/doc#944]
Considering lot's of flaming in chat about [table.sort odd result](https://github.com/tarantool/tarantool/issues/4557) and little words written within [Lua reference manual](https://www.lua.org/manual/5.1/manual.html#pdf-table.sort) about comparators to be used for sorting I propose to enrich tarantool docs related to the table.sort with several examples and rationale for a such behaviour.

**Comment by lenkis** [comment]
@kyukhin please help with examples

**Comment by pgulutzan** [comment]
This was an odd request because, as I understand it, there is no bug in table.sort() -- the example in issue#4557 simply didn't follow the instructions in the Lua manual. And we aren't in the business of fixing the Lua manual -- that's why, in the table module chapter,our interest is in describing what's in Tarantool's Lua application server that you won't find in basic Lua.

But Tarantool should have a special table.sort() anyway, because in fact there are possible table.sort() features that are of interest for Tarantool users but aren't in basic Lua. I wrote one, and put it in the manual, and I close this. What I expect is: Whenever anybody has time to spare, they will write a
better implementation of the same function, re-open this issue, and tell me what I missed. Or, perhaps somebody will decide that I didn't understand the problem (which is true, I don't), and can re-explain and re-open.
